# Generated by Django 5.0 on 2024-09-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clothes_donated_clothes_in_laundry_clothes_recycled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
