# Generated by Django 5.0 on 2024-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tobuyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('item_details', models.TextField()),
                ('item_photo', models.ImageField(upload_to='item_photos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
