# Generated by Django 5.0 on 2024-09-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
