# Generated by Django 5.0 on 2024-09-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_message_user'),
    ]

    operations = [
    ]
