# Generated by Django 5.0 on 2024-09-29 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240929_0023'),
    ]

    operations = [
    ]
